#公共配置
spring:
  profiles:
    active: peer0
eureka:
  server:
    enable-self-preservation: false #关闭自我保护模式
    eviction-interval-timer-in-ms: 5000 #清理间隔(默认是60秒)
    renewal-percent-threshold: 0.49 #自我保护系数，默认是0.85
---
spring:
  application:
    name: base-eureka-service
  profiles: peer0
server:
  port: 8000
  servlet:
    context-path: /
eureka:
  instance:
    hostname: peer0
    prefer-ip-address: false #是否用ip作为路径
  client:
    service-url:
      defaultZone: http://peer1:8001/eureka/,http://peer2:8002/eureka/
    fetch-registry: true
    register-with-eureka: true
---
spring:
  application:
    name: base-eureka-service
  profiles: peer1
server:
  port: 8001
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: false #是否用ip作为路径
  client:
    service-url:
      defaultZone: http://peer0:8000/eureka/,http://peer2:8002/eureka/
    fetch-registry: true
    register-with-eureka: true
---
spring:
  application:
    name: base-eureka-service
  profiles: peer2
server:
  port: 8002
eureka:
  instance:
    hostname: peer2
    prefer-ip-address: false #是否用ip作为路径
  client:
    service-url:
      defaultZone: http://peer0:8000/eureka/,http://peer1:8001/eureka/
    fetch-registry: true
    register-with-eureka: true